<?php

namespace AppBundle\Repository;

/**
 * GestionTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionTacheRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTaches()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:GestionTache a '
            )
            ->getResult();
    }
}
