<?php

namespace AppBundle\Repository;

/**
 * TachePiloteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TachePiloteRepository extends \Doctrine\ORM\EntityRepository
{
}
