<?php

namespace AppBundle\Repository;

/**
 * TacheAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
