<?php

namespace AppBundle\Repository;

/**
 * TacheAlgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheAlgRepository extends \Doctrine\ORM\EntityRepository
{
}
