app:
    resource: '@AppBundle/Controller/'
    type: annotation

verif:
  path:   /
  controller: AppBundle\Controller\DefaultController::loginAction

homePilote:
  path:   /formPilote
  controller: AppBundle\Controller\DefaultController::piloteAction

homeAlg:
  path:   /formAlg
  controller: AppBundle\Controller\DefaultController::algAction

homeAdmin:
  path:   /formAdmin
  controller: AppBundle\Controller\DefaultController::adminAction

suiviTache:
  path:   /suiviTache
  controller: AppBundle\Controller\DefaultController::suiviAction

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile